# Generated by Django 4.2.3 on 2023-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shippingaddress_addressone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='addressOne',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
