# Generated by Django 4.2.3 on 2023-08-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avalble_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='avalble_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='avalble_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='avalble_sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize'),
            preserve_default=False,
        ),
    ]
