# Generated by Django 4.2.3 on 2023-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_avalble_sizes_product_avalble_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avalble_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='avalble_color',
            field=models.ManyToManyField(to='shop.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Brand',
            field=models.ManyToManyField(to='shop.productbrand'),
        ),
    ]
