# Generated by Django 4.2.3 on 2023-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shippingaddress_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullName',
            new_name='full_Name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
